# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWACJzxz5Pp1FZ4Sw5pfnp5sPgMaGidr
"""

import numpy as np
import pandas as pd
from random import choice

from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_csv(filename, delim_whitespace=True, skiprows=1, names = ['x(A)','y(A)', 'z(A)'])
df.head()

df



def pbc(x,y,z, count):      #PBC cell length = n Ang
  for i in range(len(x)):
    if x[i] > n/2:
      x[i] = x[i] - n/2
      count.append(x[i])


    elif x[i] < -n/2:
      x[i] = x[i] + n/2
      count.append(x[i])


    if y[i] > n/2:
      y[i] = y[i] - n/2
      count.append(y[i])


    elif y[i] < -n/2:
      y[i] = y[i] + n/2
      count.append(y[i])

    if z[i] > n/2:
      z[i] = z[i] - n/2
      count.append(z[i])

    elif z[i] < -n/2:
      z[i] = z[i] + n/2
      count.append(z[i])

  return x,y,z


n = float(input("PBC cell length is: "))


X = df['x(A)']   #Individual columns
Y = df['y(A)']
Z = df['z(A)']

# print(X)


for i in range(len(df)):
  if df['x(A)'][i] < n and df['x(A)'][i] > -n:              #All units are in 1 Ang
    X[i] = df['x(A)'][i]
  if df['y(A)'][i] < n and df['y(A)'][i] > -n:
    Y[i] = df['y(A)'][i]
  if df['z(A)'][i] < n and df['z(A)'][i] > -n:
    Z[i] = df['z(A)'][i]

dir = [1, -1]             #For choosing +1 or -1

corr = choice(['X' , 'Y' , 'Z'])    #For choosing the coordinate

corr1 = choice(dir)

count = []   #This for counting the number of times the particle goes outside the box

for i in range(len(df)):
  if corr == 'X':
    X[i] = X[i] + int(corr1)
    pbc(X,Y,Z, count)
  elif corr == 'Y':
    Y[i] = Y[i] + int(corr1)
    pbc(X,Y,Z, count)
  elif corr == 'Z':
    Z[i] = Z[i] + int(corr1)
    pbc(X,Y,Z, count)


print(f"number of times a particle has gone out {len(count)}")

3

X1=[]   #These lists are for appending 10th coordinate
Y1=[]
Z1=[]

X2=[]   #These lists are for appending 20th coordinate
Y2=[]
Z2=[]

for j in range(20):

  count1 = []

  for i in range(len(df)):
    if corr == 'X':
      X[i] = X[i] + int(corr1)
      pbc(X,Y,Z, count1)
    elif corr == 'Y':
      Y[i] = Y[i] + int(corr1)
      pbc(X,Y,Z, count1)
    elif corr == 'Z':
      Z[i] = Z[i] + int(corr1)
      pbc(X,Y,Z, count1)

  if j == 9:
    for k in range(len(df)):
      X1.append(X[k])
      Y1.append(Y[k])
      Z1.append(Z[k])

  if j == 19:
    for k in range(len(df)):
      X2.append(X[k])
      Y2.append(Y[k])
      Z2.append(Z[k])


  # if j == 9 or j == 19:
  #   print(f"Coordinates are ({X[i]}, {Y[i]}, {Z[i]})")

  print(f"Number of particles in this iteration: {len(count1)} ")

max_x = X.max()
min_x = X.min()
max_y = Y.max()
min_y = Y.min()
max_z = Z.max()
min_z = Z.min()

print(max_x, min_x, max_y, min_y, max_z, min_z)

#Converting coordinate columns to data frame


df1 = pd.DataFrame(list(zip(X1, Y1, Z1)), columns = ['X', 'Y', 'Z'])
df1

df2 = pd.DataFrame(list(zip(X2, Y2, Z2)), columns = ['X', 'Y', 'Z'])
df2

# Converting the 10th coordinate df to txt file
df1.to_csv('data2.txt', sep=' ', index=False)

#Converting the 20th coordinate df to txt file
df2.to_csv('data3.txt', sep=' ', index=False)

df1

